# Generated by Django 3.0.7 on 2020-06-07 17:26

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified date')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('occupation', models.CharField(max_length=100, verbose_name='Cargo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified date')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('service', models.CharField(max_length=100, verbose_name='Service')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('icon', models.CharField(choices=[('lni-cog', 'Gear'), ('lni-stats-up', 'Graphic'), ('lni-users', 'Users'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Rocket')], max_length=25, verbose_name='Icon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Modified date')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('bio', models.TextField(max_length=255, verbose_name='Bio')),
                ('photo', stdimage.models.StdImageField(upload_to='team', verbose_name='Photo')),
                ('facebook', models.CharField(default='#', max_length=100, verbose_name='Facebook')),
                ('twitter', models.CharField(default='#', max_length=100, verbose_name='Twitter')),
                ('instagram', models.CharField(default='#', max_length=100, verbose_name='Instagram')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Occupation', verbose_name='Occupation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
