# Generated by Django 3.0.7 on 2020-06-07 17:51

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200607_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='Photo'),
        ),
    ]
